import "zone.js/dist/zone";
import { Component, Input } from "@angular/core";
import { CommonModule } from "@angular/common";
import { bootstrapApplication } from "@angular/platform-browser";

import { AppModule } from "../app.module";
import { AppRoutingModule } from "../app-routing.module";

@Component({
    selector: "app-layout",
    standalone: true,
    imports: [CommonModule, AppModule, AppRoutingModule],
    templateUrl: "./layout.component.html",
    styleUrls: ["./layout.component.css"]
})

export class LayoutComponent {
    name: string = "Layout";
    
    @Input() children: Node;
    
    constructor(children: Node) {
        this.children = children;
    }
}

export const metadata = {
    title: "Angular CLI",
    description: "Generated by angular-cli",
}

export const RootLayout = () => {
    document.addEventListener("DOMContentLoaded", () => {
        let children: Node = new (Node);
        children.addEventListener("load", () => {
            document.write(`
                <!DOCTYPE html>
                <html lang="en-US">
                    <head>
                        <meta charset="UTF-8">
                        <meta name="width=device-width, initial-scale=1">
                        <title>ChildrenDataCoupling</title>
                    </head>
                    <body [ngClass]="{1: 'inter'}" id="children">
                        {{ children }}
                    </body>
                </html>
            `);
        });
    document.getElementById("children");
    document.appendChild(children);
    })
}

bootstrapApplication(LayoutComponent);
